/**
 * Complete, fully-populated demo dataset for Reflection — Issue 33
 * Department of Computer Engineering
 * Academic Year 2026–27 | June – December 2026 | Published
 */

export const DEMO_MAGAZINE_METADATA = {
  id: 'MAG-2026-33',
  title: 'Reflection',
  issueNumber: 33,
  academicYear: '2026–27',
  semester: 'Annual',
  department: 'Department of Computer Engineering',
  period: 'June – December 2026',
  description: 'The 33rd edition of Reflection capturing departmental excellence, faculty research, student innovations, and academic milestones for the Department of Computer Engineering.',
  status: 'Published',
  template: 'modern-academic',
  publishedDate: '2026-12-20',
  coverColor: '#1E2D5A',
  totalPages: 22,
  tagline: 'Connecting Ideas, Innovation and Impact',
  coverImage: '/images/reflection-cover-issue33.jpg',
  sections: {
    cover: { completed: true },
    message: { completed: true },
    toppers: { completed: true },
    events: { completed: true },
    workshops: { completed: true },
    lectures: { completed: true },
    achievements: { completed: true },
    coe: { completed: true },
    staffAchievements: { completed: true },
    fdpSttp: { completed: true },
    publications: { completed: true },
  },
};

// Shuffled internally in random order to demonstrate automatic sorting by Rank 1, 2, 3
export const DEMO_TOPPERS_RANDOM_ORDER = [
  { id: 'top-18', name: 'Shreya Phadke', class: 'TE', division: 'C', rank: 3, cgpa: '9.47', photo: '/images/toppers/topper_18.svg' },
  { id: 'top-2', name: 'Ananya Patil', class: 'SE', division: 'A', rank: 2, cgpa: '9.65', photo: '/images/toppers/topper_2.svg' },
  { id: 'top-25', name: 'Shubham Jagtap', class: 'BE', division: 'C', rank: 1, cgpa: '9.89', photo: '/images/toppers/topper_25.svg' },
  { id: 'top-7', name: 'Aditya Bhosale', class: 'SE', division: 'C', rank: 1, cgpa: '9.79', photo: '/images/toppers/topper_7.svg' },
  { id: 'top-13', name: 'Omkar Gokhale', class: 'TE', division: 'B', rank: 1, cgpa: '9.84', photo: '/images/toppers/topper_13.svg' },
  { id: 'top-21', name: 'Yashwardhan Pawar', class: 'BE', division: 'A', rank: 3, cgpa: '9.61', photo: '/images/toppers/topper_21.svg' },
  { id: 'top-4', name: 'Siddhi Joshi', class: 'SE', division: 'B', rank: 1, cgpa: '9.85', photo: '/images/toppers/topper_4.svg' },
  { id: 'top-11', name: 'Kunal Sawant', class: 'TE', division: 'A', rank: 2, cgpa: '9.71', photo: '/images/toppers/topper_11.svg' },
  { id: 'top-23', name: 'Atharva Pandit', class: 'BE', division: 'B', rank: 2, cgpa: '9.75', photo: '/images/toppers/topper_23.svg' },
  { id: 'top-1', name: 'Aarav Kulkarni', class: 'SE', division: 'A', rank: 1, cgpa: '9.82', photo: '/images/toppers/topper_1.svg' },
  { id: 'top-16', name: 'Meera Iyer', class: 'TE', division: 'C', rank: 1, cgpa: '9.81', photo: '/images/toppers/topper_16.svg' },
  { id: 'top-6', name: 'Tanvi Shinde', class: 'SE', division: 'B', rank: 3, cgpa: '9.51', photo: '/images/toppers/topper_6.svg' },
  { id: 'top-27', name: 'Harshwardhan Patil', class: 'BE', division: 'C', rank: 3, cgpa: '9.55', photo: '/images/toppers/topper_27.svg' },
  { id: 'top-10', name: 'Rhea Mehta', class: 'TE', division: 'A', rank: 1, cgpa: '9.88', photo: '/images/toppers/topper_10.svg' },
  { id: 'top-3', name: 'Rohan Deshmukh', class: 'SE', division: 'A', rank: 3, cgpa: '9.48', photo: '/images/toppers/topper_3.svg' },
  { id: 'top-20', name: 'Kavya Venkataraman', class: 'BE', division: 'A', rank: 2, cgpa: '9.78', photo: '/images/toppers/topper_20.svg' },
  { id: 'top-8', name: 'Isha More', class: 'SE', division: 'C', rank: 2, cgpa: '9.62', photo: '/images/toppers/topper_8.svg' },
  { id: 'top-14', name: 'Gauri Chitale', class: 'TE', division: 'B', rank: 2, cgpa: '9.66', photo: '/images/toppers/topper_14.svg' },
  { id: 'top-22', name: 'Divya Tambe', class: 'BE', division: 'B', rank: 1, cgpa: '9.91', photo: '/images/toppers/topper_22.svg' },
  { id: 'top-5', name: 'Pranav Kadam', class: 'SE', division: 'B', rank: 2, cgpa: '9.68', photo: '/images/toppers/topper_5.svg' },
  { id: 'top-17', name: 'Tejas Salunkhe', class: 'TE', division: 'C', rank: 2, cgpa: '9.63', photo: '/images/toppers/topper_17.svg' },
  { id: 'top-26', name: 'Rupali Jadhav', class: 'BE', division: 'C', rank: 2, cgpa: '9.72', photo: '/images/toppers/topper_26.svg' },
  { id: 'top-9', name: 'Varun Gaikwad', class: 'SE', division: 'C', rank: 3, cgpa: '9.45', photo: '/images/toppers/topper_9.svg' },
  { id: 'top-19', name: 'Vikramaditya Mane', class: 'BE', division: 'A', rank: 1, cgpa: '9.94', photo: '/images/toppers/topper_19.svg' },
  { id: 'top-12', name: 'Pooja Nair', class: 'TE', division: 'A', rank: 3, cgpa: '9.54', photo: '/images/toppers/topper_12.svg' },
  { id: 'top-24', name: 'Neha Inamdar', class: 'BE', division: 'B', rank: 3, cgpa: '9.58', photo: '/images/toppers/topper_24.svg' },
  { id: 'top-15', name: 'Siddharth Rao', class: 'TE', division: 'B', rank: 3, cgpa: '9.50', photo: '/images/toppers/topper_15.svg' },
];

export const DEMO_MAGAZINE_SECTION_DATA = {
  cover: {
    title: 'Reflection',
    issueNumber: 33,
    academicYear: '2026–27',
    department: 'Department of Computer Engineering',
    tagline: 'Connecting Ideas, Innovation and Impact',
    collegeLogo: '/images/college-logo.jpg',
    coverImage: '/images/reflection-cover-issue33.jpg',
    overlay: {
      type: 'none',
      color: '#000000',
      opacity: 0,
      gradientStart: '#1E2D5A',
      gradientEnd: '#0D1B2A',
    },
  },
  message: {
    principal: {
      name: 'Dr. S. V. Kulkarni',
      designation: 'Principal, MES Wadia College of Engineering',
      photo: '/images/college-emblem.jpg',
      message: `I am delighted to extend my warmest congratulations to the Department of Computer Engineering on the release of Issue 33 of their premier annual publication, 'Reflection'.\n\nIn this epoch of unprecedented technological acceleration, our institution remains dedicated to fostering an ecosystem where rigorous engineering inquiry and societal empathy converge. The students and faculty of Computer Engineering have continually exemplified this vision through their distinction in competitive national hackathons, high-impact research publications, and innovative technological prototypes.\n\nThis magazine serves as a mirror reflecting our shared aspirations, milestones, and collaborative spirit. I commend the Head of Department Dr. Neha Sharma, the editorial committee, and all student contributors for crafting an exemplary volume that inspires the entire academic community.`,
    },
    hod: {
      name: 'Dr. Neha Sharma',
      designation: 'Head of Department, Department of Computer Engineering',
      photo: '/images/hod-neha-sharma.jpg',
      message: `It is my distinct privilege and honor to present Issue 33 of 'Reflection', the flagship publication of the Department of Computer Engineering for the academic period June – December 2026.\n\nThis semester has witnessed extraordinary academic growth, student innovation, and vibrant industry collaboration. Through modernized curricula, high-performance computing labs, and industry-sponsored hackathons, our undergraduate and postgraduate students have pushed technical boundaries, earning top honors at Smart India Hackathon, ACM ICPC, and the Microsoft Imagine Cup.\n\nOur faculty members continue to expand the horizons of engineering knowledge, securing substantial government research grants, publishing in premier IEEE and Elsevier journals, and receiving granted Indian patents. Furthermore, our state-of-the-art Centre of Excellence in Extended Reality and Emerging Technologies in partnership with Meta Platforms and Unity is now actively training our students in spatial computing and neural rendering.\n\nAs we prepare our engineers for an AI-augmented global workforce, our departmental goal remains unwavering: nurturing compassionate problem solvers equipped with deep technical acumen, ethical integrity, and visionary leadership. I extend my sincere gratitude to our students, faculty, alumni, and leadership for making this edition a true testament to our shared excellence.`,
    },
  },
  toppers: {
    students: DEMO_TOPPERS_RANDOM_ORDER,
  },
  events: [
    {
      id: 101,
      title: 'INNOVEX 2026: National Technical Symposium',
      date: '15–16 September 2026',
      venue: 'Dr. A.P.J. Abdul Kalam Auditorium & Labs',
      organizer: 'Association of Computer Engineering Students (ACES)',
      participants: 380,
      description: 'The flagship national symposium featured inter-collegiate coding marathons, paper presentations in AI/ML, web development hackathons, and hardware-software co-design competitions with participants from over 45 universities.',
      photos: [
        { url: '/images/event-symposium.jpg', caption: 'Keynote address & project demonstrations at INNOVEX 2026' },
        { url: '/images/demo/event-project-showcase.svg', caption: 'Student IoT & robotics showcase arena' },
      ],
      layout: 'Large Image + Text',
    },
    {
      id: 102,
      title: 'ByteQuest 2026: 7-Day Algorithmic Challenge Week',
      date: '3–7 August 2026',
      venue: 'Department Compute Cluster & Online HackerRank',
      organizer: 'CodeChef Campus Chapter & Department of Comp Engg',
      participants: 240,
      description: 'An intensive week of algorithmic problem solving, time-complexity optimization, and live debug-a-thons designed to sharpen data structures and algorithmic thinking for upcoming tier-1 placement drives.',
      photos: [
        { url: '/images/demo/event-coding-week.svg', caption: 'Competitive coding leaderboard and live submissions' },
      ],
      layout: 'Text + Image',
    },
    {
      id: 103,
      title: 'TechConnect 2026: Industry Interaction Day',
      date: '9 October 2026',
      venue: 'Campus Convention Centre',
      organizer: 'Training & Placement Cell & Computer Engineering Faculty',
      participants: 310,
      description: 'Senior engineering directors and talent leaders from Google, Microsoft, NVIDIA, and Persistent Systems engaged in panel discussions on next-generation system architecture, site reliability, and industry hiring standards.',
      photos: [
        { url: '/images/demo/event-industry-day.svg', caption: 'Panel discussion on industry architectural shifts' },
      ],
      layout: 'Two Image Grid',
    },
    {
      id: 104,
      title: 'Capstone Innovation & Project Showcase 2026',
      date: '18 November 2026',
      venue: 'Department Labs 1–4',
      organizer: 'Institution Innovation Council (IIC)',
      participants: 190,
      description: 'Over 60 final-year BE capstone teams presented live working prototypes spanning healthcare diagnostics, edge computing in agriculture, blockchain traceability, and quantum algorithms to an external jury of industry veterans.',
      photos: [
        { url: '/images/demo/event-project-showcase.svg', caption: 'Live project evaluation by industry technical jury' },
      ],
      layout: 'Large Image + Text',
    },
    {
      id: 105,
      title: 'Pulse 2026: Annual Department Day Celebration',
      date: '18 December 2026',
      venue: 'Main College Amphitheatre',
      organizer: 'Student Council & Department Cultural Committee',
      participants: 450,
      description: 'An inspiring evening celebrating academic toppers, faculty research achievements, student leadership, and cultural performances, culminating in the formal distribution of departmental honors.',
      photos: [
        { url: '/images/demo/event-annual-day.svg', caption: 'Annual departmental awards ceremony and student showcase' },
      ],
      layout: 'Large Image + Text',
    },
  ],
  workshops: [
    {
      id: 201,
      title: 'Generative AI and Large Language Model Engineering',
      date: '10–11 July 2026',
      speaker: 'Dr. Arvind Narayanan',
      designation: 'Senior Staff Research Scientist',
      organization: 'Google DeepMind',
      venue: 'Advanced Computing Lab 1',
      targetClass: 'TE & BE',
      participants: 85,
      description: 'Hands-on exploration of transformer architectures, attention mechanisms, fine-tuning Llama-3 and Gemma models using LoRA/QLoRA, retrieval-augmented generation (RAG) pipelines, and LangChain orchestration.',
      photos: [
        { url: '/images/workshop-genai.jpg', caption: 'Dr. Arvind Narayanan demonstrating live RAG pipelines' },
      ],
    },
    {
      id: 202,
      title: 'Blockchain Protocols & Decentralized Smart Contracts',
      date: '21–22 August 2026',
      speaker: 'Mr. Sahil Deshmukh',
      designation: 'Core Protocol Engineer',
      organization: 'Polygon Labs',
      venue: 'High Performance Lab 2',
      targetClass: 'SE, TE & BE',
      participants: 78,
      description: 'Practical training on Ethereum Virtual Machine (EVM), Solidity smart contract security patterns, decentralized finance protocols, zero-knowledge rollups, and Hardhat development environments.',
      photos: [
        { url: '/images/demo/workshop-blockchain.svg', caption: 'Live smart contract deployment and audit workshop' },
      ],
    },
    {
      id: 203,
      title: 'Full Stack Web Engineering with React 19 & Microservices',
      date: '11–12 September 2026',
      speaker: 'Ms. Radhika Kulkarni',
      designation: 'VP of Engineering',
      organization: 'Thoughtworks India',
      venue: 'Software Systems Lab',
      targetClass: 'SE & TE',
      participants: 92,
      description: 'Modern full-stack paradigms covering React 19 Server Components, Next.js App Router, gRPC microservice communication, Docker containerization, and automated CI/CD deployment on cloud clusters.',
      photos: [
        { url: '/images/demo/workshop-fullstack.svg', caption: 'Microservice architecture and React 19 hands-on lab' },
      ],
    },
    {
      id: 204,
      title: 'Cybersecurity, Threat Modeling & Ethical Hacking Bootcamp',
      date: '16–17 October 2026',
      speaker: 'Mr. Vivek Ranade',
      designation: 'Chief Information Security Officer',
      organization: 'CyberShield Technologies',
      venue: 'Network Security Lab',
      targetClass: 'TE & BE',
      participants: 74,
      description: 'Hands-on penetration testing, web application security (OWASP Top 10), network traffic packet inspection with Wireshark, privilege escalation, and active defensive hardening on isolated sandbox targets.',
      photos: [
        { url: '/images/demo/workshop-cybersecurity.svg', caption: 'Red team vs. blue team live ethical hacking simulation' },
      ],
    },
  ],
  lectures: [
    {
      id: 301,
      topic: 'Strategic Career Roadmaps in Distributed Systems & Artificial Intelligence',
      title: 'Careers in Emerging Technologies: AI, Cloud, and Beyond',
      speaker: 'Dr. Prashant Borkar',
      designation: 'Principal Research Director',
      organization: 'Microsoft Research India, Bengaluru',
      date: '24 July 2026',
      venue: 'Central Seminar Hall',
      targetClass: 'SE, TE & BE',
      participants: 280,
      description: 'An inspiring lecture dissecting future skills demanded by top global tech companies, the shift toward autonomous software agents, and practical advice on balancing fundamental computer science theory with applied engineering.',
      photos: [
        { url: '/images/guest-lecture-ai.jpg', caption: 'Dr. Prashant Borkar engaging with engineering students' },
      ],
    },
    {
      id: 302,
      topic: 'Enterprise Distributed Ledgers and Transparent Global Supply Chains',
      title: 'Blockchain Beyond Cryptocurrency',
      speaker: 'Ms. Rajeshwari Verma',
      designation: 'Lead Blockchain Architect',
      organization: 'Hyperledger Foundation & IBM',
      date: '14 August 2026',
      venue: 'Department Seminar Hall',
      targetClass: 'TE & BE',
      participants: 160,
      description: 'A deep architectural dive into permissioned ledgers, Byzantine fault tolerance, supply chain traceability, tamper-proof audit trails, and the legal framework governing enterprise Web3 deployments.',
      photos: [
        { url: '/images/demo/guest-lecture-blockchain.svg', caption: 'Technical session on Hyperledger fabric architecture' },
      ],
    },
    {
      id: 303,
      topic: 'Production Machine Learning and Billion-Parameter Model Serving at Scale',
      title: 'AI Engineering in Industry: From Prototypes to Scale',
      speaker: 'Mr. Ankit Srivastava',
      designation: 'Director of Engineering',
      organization: 'NVIDIA India',
      date: '25 September 2026',
      venue: 'Seminar Hall 2',
      targetClass: 'TE & BE',
      participants: 210,
      description: 'Explored hardware acceleration, CUDA tensor cores, vLLM inference engines, model quantization strategies (FP8/INT4), and techniques for achieving ultra-low latency serving in high-concurrency enterprise products.',
      photos: [
        { url: '/images/demo/guest-lecture-careers.svg', caption: 'GPU cluster scaling lecture for engineering undergraduates' },
      ],
    },
    {
      id: 304,
      topic: 'From Campus Ideas to Scale: The Zero-to-One Venture Blueprint',
      title: 'Building Tech Products from Student Ideas',
      speaker: 'Ms. Tanvi Chordia',
      designation: 'Managing Partner & Angel Investor',
      organization: 'Nexus Venture Catalysts',
      date: '6 November 2026',
      venue: 'Campus Incubation Centre',
      targetClass: 'SE, TE & BE',
      participants: 195,
      description: 'Actionable guidance on user research, minimum viable product (MVP) design, customer discovery, institutional seed funding, and turning engineering capstone projects into sustainable tech ventures.',
      photos: [
        { url: '/images/demo/guest-lecture-products.svg', caption: 'Student entrepreneurship workshop and pitch clinic' },
      ],
    },
  ],
  achievements: [
    {
      id: 401,
      name: 'Ketan Patil & Team TechNova',
      class: 'BE Div A',
      achievement: 'Smart India Hackathon (SIH 2026) — 1st Prize Winner',
      level: 'National Level',
      position: '1st Place Winner',
      prize: '₹1,00,000 Cash Prize + Trophy',
      date: 'September 2026',
      description: 'Won the nationwide hackathon organized by the Ministry of Education with an AI-powered automated grievance routing and sentiment analysis engine for municipal corporations.',
      photo: '/images/hackathon-winners.jpg',
    },
    {
      id: 402,
      name: 'Vikramaditya Mane',
      class: 'BE Div A',
      achievement: 'ACM International Collegiate Programming Contest (ICPC)',
      level: 'National Level',
      position: '12th Rank Nationwide',
      prize: 'Regional Finalist Medal',
      date: 'November 2026',
      description: 'Ranked 12th out of 1,200+ collegiate teams at the Amritapuri ICPC Asia-West Regional Contest, solving 8 complex algorithmic problems within five hours.',
      photo: '/images/demo/achievement-icpc.svg',
    },
    {
      id: 403,
      name: 'Rhea Mehta & Team HoloSurg',
      class: 'TE Div A',
      achievement: 'Microsoft Imagine Cup 2026',
      level: 'National Level',
      position: 'Top 5 National Finalist',
      prize: 'Azure Sponsorship + $5,000 Credits',
      date: 'October 2026',
      description: 'Engineered an augmented reality surgical navigation headset prototype that overlays patient 3D CT scans in real time during orthopaedic operations.',
      photo: '/images/demo/achievement-imaginecup.svg',
    },
    {
      id: 404,
      name: 'Yashwardhan Pawar',
      class: 'BE Div A',
      achievement: 'IEEE International Student Research Conference',
      level: 'International Level',
      position: 'Best Research Paper Award',
      prize: 'Gold Certificate & Honorarium',
      date: 'August 2026',
      description: 'Authored and presented peer-reviewed research on "Cryptographic Acceleration on RISC-V Custom Hardware" at the IEEE International Symposium in Singapore.',
      photo: '/images/demo/achievement-research.svg',
    },
    {
      id: 405,
      name: 'Kunal Sawant',
      class: 'TE Div A',
      achievement: 'National Cyber Shield Capture the Flag (CTF) 2026',
      level: 'National Level',
      position: '1st Runner-Up',
      prize: '₹40,000 + CyberShield Certification',
      date: 'July 2026',
      description: 'Secured 2nd place among 450 competitive ethical hacking teams nationwide, demonstrating superior skills in binary exploitation, reverse engineering, and web vulnerabilities.',
      photo: '/images/demo/achievement-cyber.svg',
    },
    {
      id: 406,
      name: 'Pranav Kadam',
      class: 'SE Div B',
      achievement: 'Indian Patent Publication: Autonomous Smart Irrigation Drone',
      level: 'National Level',
      position: 'Patent Published',
      prize: 'Official Patent Journal Gazetted',
      date: 'October 2026',
      description: 'Invented an edge AI drone system capable of multispectral crop stress mapping and targeted micro-fertilizer dispensation. Patent Application No. 202621045678.',
      photo: '/images/demo/achievement-patent.svg',
    },
    {
      id: 407,
      name: 'Shubham Jagtap',
      class: 'BE Div C',
      achievement: 'IIT Bombay Techfest Autonomous Robotics Challenge',
      level: 'National Level',
      position: '2nd Place',
      prize: 'Silver Trophy + ₹25,000',
      date: 'December 2026',
      description: 'Constructed an autonomous mobile robot featuring SLAM LiDAR navigation, stereo depth perception, and real-time obstacle evasion through dynamic search algorithms.',
      photo: '/images/demo/achievement-robotics.svg',
    },
    {
      id: 408,
      name: 'Divya Tambe',
      class: 'BE Div B',
      achievement: 'AWS Certified Solutions Architect — Professional',
      level: 'International Level',
      position: 'Certified (100% Score)',
      prize: 'Professional Credential Badge',
      date: 'August 2026',
      description: 'Achieved a perfect score in the rigorous AWS Certified Solutions Architect Professional exam, validating master-level expertise in complex distributed cloud systems.',
      photo: '/images/demo/achievement-cloud.svg',
    },
    {
      id: 409,
      name: 'Aarav Kulkarni',
      class: 'SE Div A',
      achievement: 'SPPU Inter-Collegiate Coding Championship 2026',
      level: 'University Level',
      position: 'Gold Medalist (1st Place)',
      prize: 'University Trophy & Gold Medal',
      date: 'September 2026',
      description: 'Secured 1st rank among 300 engineering students across Savitribai Phule Pune University in an intensive 4-hour advanced algorithmic contest.',
      photo: '/images/toppers/topper_1.svg',
    },
    {
      id: 410,
      name: 'Siddharth Rao',
      class: 'TE Div B',
      achievement: 'Google Play Campus Innovation Award: Smart Transit App',
      level: 'State Level',
      position: 'State Innovation Winner',
      prize: 'Citation + 100,000+ Downloads',
      date: 'November 2026',
      description: 'Developed "PMPML Live", an open-source municipal transit tracking app utilizing crowd-sourced GPS telemetry, currently utilized by over 100,000 daily Pune commuters.',
      photo: '/images/demo/achievement-app.svg',
    },
  ],
  coe: {
    name: 'Centre of Excellence in Extended Reality and Emerging Technologies',
    dateEstablished: '2024-03-15',
    partner: 'Meta Platforms & Unity Technologies',
    tagline: 'Pioneering Spatial Computing, Generative AI, and Next-Gen Immersive Simulation',
    objective: 'To advance applied research, specialized undergraduate curriculum, and industry-sponsored prototyping in spatial computing, virtual reality medical simulations, and neural rendering architectures.',
    vision: 'To become a globally recognized regional node of excellence for spatial computing, equipping engineers with cutting-edge immersive software design competencies.',
    mission: 'Bridge academic research with industrial XR deployments, empower students through industry-certified curriculum tracks, and deliver impactful high-fidelity simulation tools for healthcare, education, and defense.',
    industryCollaboration: 'Active collaborative framework with Meta Platforms and Unity Technologies providing enterprise HMD hardware, high-compute GPU rendering clusters, and dedicated industrial mentor reviews for student projects.',
    description: 'The Centre of Excellence in Extended Reality and Emerging Technologies was established under a joint Memorandum of Understanding with industry partners. Equipped with state-of-the-art Meta Quest 3 HMDs, HTC Vive Pro Enterprise systems, spatial audio rigs, and NVIDIA RTX high-compute rendering clusters, the lab serves as an interdisciplinary playground for breakthrough student and faculty projects.',
    activities: '1. Meta & Unity Certified Spatial Computing Bootcamp (120 students certified).\n2. 48-Hour Healthcare XR Hackathon in partnership with Apollo Hospitals.\n3. Sponsored Research in Real-Time 3D Gaussian Splatting and NeRF models.\n4. Weekly Hands-on workshops in Unreal Engine 5 and WebXR interfaces.',
    achievements: '1. Received ₹25 Lakhs industry-sponsored equipment grant from partner consortium.\n2. Student team developed "HoloSurg XR", selected for National Innovation Conclave.\n3. Published 4 research papers in IEEE VR and ACM SIGGRAPH regional proceedings.\n4. Facilitated 14 high-impact internships with leading AR/VR design studios.',
    futurePlans: 'Expanding compute nodes for distributed generative 3D modeling, launching an enterprise Digital Twin incubation incubator, and establishing a patent translation pipeline for commercial XR applications.',
    photos: [
      { url: '/images/coe-xr-lab.jpg', caption: 'Undergraduate engineers testing spatial interactions in the XR Lab' },
      { url: '/images/demo/coe-vr-simulation.svg', caption: 'High-fidelity immersive VR simulation suite' },
      { url: '/images/demo/coe-hardware-rig.svg', caption: 'NVIDIA RTX Enterprise GPU compute clusters' },
      { url: '/images/demo/coe-industry-meta.svg', caption: 'Industry partner Meta & Unity research certification hub' },
      { url: '/images/demo/coe-student-project.svg', caption: 'Medical HoloSurg surgical planning prototype in action' },
    ],
  },
  staffAchievements: [
    {
      id: 501,
      facultyName: 'Dr. Neha Sharma',
      designation: 'Head of Department & Professor',
      achievements: [
        {
          id: 'sa-1',
          type: 'Patent Granted',
          title: 'Granted Indian Patent: Edge AI Architecture for Smart Energy Grids',
          organization: 'Patent Office of India (Patent No. 498721)',
          date: 'March 2026',
          description: 'Awarded a 20-year Indian patent for an adaptive decentralized neural control system optimizing power load distribution across heterogeneous renewable microgrids.',
          photo: '/images/demo/faculty-patent.svg',
        },
      ],
    },
    {
      id: 502,
      facultyName: 'Dr. N. F. Shaikh',
      designation: 'Professor',
      achievements: [
        {
          id: 'sa-2',
          type: 'Award & Recognition',
          title: 'IEEE Senior Member Elevation & Best Paper Award (ICICT 2026)',
          organization: 'IEEE & NIT Surathkal',
          date: 'February 2026',
          description: 'Elevated to the prestigious grade of IEEE Senior Member in recognition of a decade of significant technical and leadership contributions in distributed network systems.',
          photo: '/images/faculty-award.jpg',
        },
      ],
    },
    {
      id: 503,
      facultyName: 'Dr. A. V. Deshmukh',
      designation: 'Associate Professor',
      achievements: [
        {
          id: 'sa-3',
          type: 'Award & Recognition',
          title: 'Ph.D. Degree Conferred in Quantum Machine Learning',
          organization: 'Indian Institute of Technology (IIT) Bombay',
          date: 'July 2026',
          description: 'Successfully defended doctoral thesis titled "Variational Quantum Circuit Optimization for Combinatorial Graph Optimization Problems" under joint IIT Bombay mentorship.',
          photo: '/images/demo/faculty-phd.svg',
        },
      ],
    },
    {
      id: 504,
      facultyName: 'Prof. R. K. Joshi',
      designation: 'Assistant Professor',
      achievements: [
        {
          id: 'sa-4',
          type: 'Research Publication',
          title: 'AICTE Research Promotion Scheme (RPS) Grant of ₹18.5 Lakhs',
          organization: 'All India Council for Technical Education (AICTE), New Delhi',
          date: 'August 2026',
          description: 'Secured competitive federal funding for establishing an Edge Vision and Autonomous IoT Sensor Systems laboratory for precision agriculture.',
          photo: '/images/demo/faculty-grant.svg',
        },
      ],
    },
    {
      id: 505,
      facultyName: 'Prof. S. M. Kulkarni',
      designation: 'Associate Professor',
      achievements: [
        {
          id: 'sa-5',
          type: 'Award & Recognition',
          title: 'NPTEL National Topper & Gold Medalist: Distributed Cloud Systems',
          organization: 'Ministry of Education & IIT Kharagpur',
          date: 'October 2026',
          description: 'Ranked 1st nationally among 14,000 candidates with a score of 98% in the elite 12-week NPTEL advanced distributed cloud computing certification.',
          photo: '/images/demo/faculty-nptel.svg',
        },
      ],
    },
    {
      id: 506,
      facultyName: 'Dr. M. P. Wagh',
      designation: 'Professor',
      achievements: [
        {
          id: 'sa-6',
          type: 'Book / Chapter Published',
          title: 'Authored Textbook: Applied NLP and LLM Architectures',
          organization: 'Springer Nature Singapore (ISBN: 978-981-19-8921-4)',
          date: 'September 2026',
          description: 'Authored a comprehensive 420-page university textbook covering linguistic parsing, attention models, and production LLMOps pipelines.',
          photo: '/images/demo/faculty-author.svg',
        },
      ],
    },
    {
      id: 507,
      facultyName: 'Prof. P. R. Chavan',
      designation: 'Assistant Professor',
      achievements: [
        {
          id: 'sa-7',
          type: 'Conference Presentation',
          title: 'International Keynote Speaker at ACM Cyber-Physical Systems Conclave',
          organization: 'ACM Singapore Chapter & Nanyang Technological University',
          date: 'November 2026',
          description: 'Delivered an invited 60-minute keynote on hardware Trojan mitigation and side-channel vulnerability analysis in IoT microcontrollers.',
          photo: '/images/demo/faculty-keynote.svg',
        },
      ],
    },
    {
      id: 508,
      facultyName: 'Prof. K. S. Tambe',
      designation: 'Assistant Professor',
      achievements: [
        {
          id: 'sa-8',
          type: 'Award & Recognition',
          title: 'University Best Teacher Award 2026 for Pedagogical Excellence',
          organization: 'Savitribai Phule Pune University (SPPU)',
          date: 'September 2026',
          description: 'Conferred the prestigious University Best Teacher Award for outstanding student mentoring, innovative project-based learning methods, and curriculum innovation.',
          photo: '/images/faculty-award.jpg',
        },
      ],
    },
  ],
  fdpSttp: [
    {
      id: 601,
      facultyName: 'Dr. Neha Sharma',
      activity: 'Executive Leadership in Higher Education & Academic Governance',
      organization: 'Indian Institute of Management (IIM) Ahmedabad',
      startDate: '05-Jul-2026',
      endDate: '10-Jul-2026',
      mode: 'Offline',
      duration: '1 Week',
      description: 'Strategic management, NEP 2020 integration, research commercialization, and institutional capacity building.',
    },
    {
      id: 602,
      facultyName: 'Dr. N. F. Shaikh',
      activity: 'Advanced Deep Learning & Generative Architectures',
      organization: 'IIT Bombay — NPTEL-AICTE',
      startDate: '01-Jun-2026',
      endDate: '28-Jun-2026',
      mode: 'Online',
      duration: '4 Weeks',
      description: 'Diffusion models, variational autoencoders, multi-head attention mechanisms, and distributed PyTorch training.',
    },
    {
      id: 603,
      facultyName: 'Prof. R. K. Joshi',
      activity: 'Cloud-Native Kubernetes & Microservices Architecture',
      organization: 'Veermata Jijabai Technological Institute (VJTI) Mumbai',
      startDate: '10-Aug-2026',
      endDate: '14-Aug-2026',
      mode: 'Offline',
      duration: '1 Week',
      description: 'Service mesh configurations, container security, Istio ingress management, and GitOps workflows.',
    },
    {
      id: 604,
      facultyName: 'Prof. S. M. Kulkarni',
      activity: 'Outcome-Based Pedagogical Engineering & Accreditation',
      organization: 'AICTE-NITTT Chennai',
      startDate: '01-Sep-2026',
      endDate: '21-Sep-2026',
      mode: 'Online',
      duration: '3 Weeks',
      description: 'Formulation of course learning outcomes, Bloom taxonomy assessment rubrics, and continuous evaluation systems.',
    },
    {
      id: 605,
      facultyName: 'Dr. A. V. Deshmukh',
      activity: 'Quantum Information Processing & Quantum Computing',
      organization: 'Indian Institute of Science (IISc) Bengaluru',
      startDate: '17-Aug-2026',
      endDate: '22-Aug-2026',
      mode: 'Hybrid',
      duration: '1 Week',
      description: 'Quantum superposition algorithms, Qiskit framework programming, and quantum error mitigation strategies.',
    },
    {
      id: 606,
      facultyName: 'Prof. P. R. Chavan',
      activity: 'Cyber-Physical Embedded Systems & Hardware Security',
      organization: 'National Institute of Technology (NIT) Raipur',
      startDate: '12-Oct-2026',
      endDate: '16-Oct-2026',
      mode: 'Hybrid',
      duration: '1 Week',
      description: 'Side-channel attack defense, secure boot firmware verification, and RISC-V enclave hardware implementations.',
    },
    {
      id: 607,
      facultyName: 'Prof. K. S. Tambe',
      activity: 'Modern Web Frameworks & Full-Stack Cloud Deployments',
      organization: 'International Institute of Information Technology (IIIT) Hyderabad',
      startDate: '07-Sep-2026',
      endDate: '12-Sep-2026',
      mode: 'Online',
      duration: '1 Week',
      description: 'React 19 architectures, Next.js server actions, GraphQL schema design, and serverless compute deployments.',
    },
    {
      id: 608,
      facultyName: 'Dr. M. P. Wagh',
      activity: 'Natural Language Processing with Transformers & LLMOps',
      organization: 'Indian Institute of Technology (IIT) Madras',
      startDate: '14-Jul-2026',
      endDate: '19-Jul-2026',
      mode: 'Offline',
      duration: '1 Week',
      description: 'Parameter-efficient fine-tuning, evaluation metrics for generative models, and guardrail architectures.',
    },
    {
      id: 609,
      facultyName: 'Prof. V. D. Patil',
      activity: 'High-Performance GPU Computing with CUDA & OpenCL',
      organization: 'Centre for Development of Advanced Computing (C-DAC) Pune',
      startDate: '23-Nov-2026',
      endDate: '27-Nov-2026',
      mode: 'Offline',
      duration: '1 Week',
      description: 'Parallel kernel optimization, memory bandwidth tuning, and multi-GPU cluster scaling on PARAM systems.',
    },
    {
      id: 610,
      facultyName: 'Prof. G. B. Shinde',
      activity: 'Blockchain Protocols and Decentralized Finance Systems',
      organization: 'Indian Institute of Technology (IIT) Roorkee',
      startDate: '03-Aug-2026',
      endDate: '08-Aug-2026',
      mode: 'Online',
      duration: '1 Week',
      description: 'Consensus mechanisms, zero-knowledge proofs, decentralized autonomous organizations (DAOs), and tokenomics.',
    },
  ],
  publications: [
    {
      id: 701,
      facultyName: 'Dr. Neha Sharma, Dr. N. F. Shaikh',
      title: 'Privacy-Preserving Federated Learning in Heterogeneous IoT Networks with Adaptive Differential Privacy',
      journal: 'IEEE Access, Vol. 14, pp. 84210–84225',
      type: 'Journal Article',
      date: 'August 2026',
      doi: '10.1109/ACCESS.2026.3129841',
      url: 'https://doi.org/10.1109/ACCESS.2026.3129841',
      description: 'Impact Factor: 3.9, Q1 Journal. Formulates an adaptive gradient noise injection mechanism mitigating adversarial inference attacks in edge computing.',
    },
    {
      id: 702,
      facultyName: 'Prof. R. K. Joshi, Dr. A. B. Patil',
      title: 'Automated Crop Disease Detection using Vision Transformers and Edge Compute Units',
      journal: 'Springer Nature Communications in Computer and Information Science, Vol. 1982',
      type: 'Conference Paper',
      date: 'September 2026',
      doi: '10.1007/978-981-19-1234-5_18',
      url: 'https://doi.org/10.1007/978-981-19-1234-5_18',
      description: 'Presented at ICICT 2026. Achieves 97.4% precision in classifying 14 foliar crop diseases directly on battery-constrained drone edge hardware.',
    },
    {
      id: 703,
      facultyName: 'Dr. A. V. Deshmukh, Prof. S. M. Kulkarni',
      title: 'Quantum-Classical Hybrid Optimisation Algorithms for NP-Hard Graph Partitioning',
      journal: 'Elsevier Journal of Computational Science, Vol. 78, Art. 102145',
      type: 'Journal Article',
      date: 'October 2026',
      doi: '10.1016/j.jocs.2026.102145',
      url: 'https://doi.org/10.1016/j.jocs.2026.102145',
      description: 'Impact Factor: 3.8, Q1 Scopus Indexed. Demonstrates quadratic speedup using QAOA variational ansatzes on simulated quantum hardware.',
    },
    {
      id: 704,
      facultyName: 'Dr. M. P. Wagh, Prof. P. R. Chavan',
      title: 'Contextual Semantic Disambiguation in Indic Languages Using Fine-Tuned Transformer Ensembles',
      journal: 'ACM Transactions on Asian and Low-Resource Language Information Processing, Vol. 25, Issue 4',
      type: 'Journal Article',
      date: 'July 2026',
      doi: '10.1145/3612845',
      url: 'https://doi.org/10.1145/3612845',
      description: 'Addresses complex polysemy in Marathi and Hindi corpora through cross-lingual word embeddings and dual-encoder attention networks.',
    },
    {
      id: 705,
      facultyName: 'Dr. N. F. Shaikh, Vikramaditya Mane (Student)',
      title: 'Zero-Knowledge Proof Verification for Decentralized Identity in Healthcare Systems',
      journal: 'Proceedings of the IEEE International Conference on Blockchain (Blockchain 2026)',
      type: 'Conference Paper',
      date: 'November 2026',
      doi: '10.1109/Blockchain56234.2026',
      url: 'https://doi.org/10.1109/Blockchain56234.2026',
      description: 'Winner of Best Student Track Paper Award. Implements zk-SNARK protocols allowing cryptographic patient credential verification without exposing medical records.',
    },
    {
      id: 706,
      facultyName: 'Prof. S. M. Kulkarni',
      title: 'Fault-Tolerant Scheduling for Distributed Microservices on Heterogeneous Edge Nodes',
      journal: 'Springer Lecture Notes in Electrical Engineering, Chapter 14, pp. 315–334',
      type: 'Book Chapter',
      date: 'September 2026',
      doi: '10.1007/978-981-15-5678-9_24',
      url: 'https://doi.org/10.1007/978-981-15-5678-9_24',
      description: 'Peer-reviewed book chapter addressing dynamic container migration under severe network jitter in industrial IoT mesh deployments.',
    },
    {
      id: 707,
      facultyName: 'Prof. K. S. Tambe, Rhea Mehta (Student)',
      title: 'Real-Time Spatial Object Detection for Augmented Reality Assistive Systems',
      journal: 'Procedia Computer Science (Elsevier), Vol. 235, pp. 412–421',
      type: 'Conference Paper',
      date: 'October 2026',
      doi: '10.1016/j.procs.2026.08.112',
      url: 'https://doi.org/10.1016/j.procs.2026.08.112',
      description: 'Presents an ultra-lightweight depth-aware convolutional model optimized for low-power AR eyeglasses assisting visually impaired users.',
    },
    {
      id: 708,
      facultyName: 'Dr. Neha Sharma, Prof. V. D. Patil',
      title: 'Scalable GPU-Accelerated Graph Neural Networks for Financial Fraud Identification',
      journal: 'Expert Systems with Applications (Elsevier), Vol. 248, Art. 118950',
      type: 'Journal Article',
      date: 'June 2026',
      doi: '10.1016/j.eswa.2026.118950',
      url: 'https://doi.org/10.1016/j.eswa.2026.118950',
      description: 'Impact Factor: 8.5, Top Tier Q1. Proposes temporal relational graph convolutional networks processing 50,000 credit transactions per second with 99.1% recall.',
    },
    {
      id: 709,
      facultyName: 'Prof. R. K. Joshi',
      title: 'Edge Computing Paradigms for Autonomous Drone Navigation in Smart Agriculture',
      journal: 'In: Edge Intelligence and Cyber-Physical Systems, CRC Press (Taylor & Francis), pp. 142–165',
      type: 'Book Chapter',
      date: 'November 2026',
      doi: '10.1201/9781003456789-7',
      url: 'https://doi.org/10.1201/9781003456789-7',
      description: 'Detailed analysis of embedded sensor telemetry, real-time path planning, and energy-aware compute offloading in agricultural robotics.',
    },
    {
      id: 710,
      facultyName: 'Prof. P. R. Chavan, Yashwardhan Pawar (Student)',
      title: 'Lightweight Cryptographic Primitive Implementations on RISC-V Microcontrollers',
      journal: 'IEEE Embedded Systems Letters, Vol. 18, No. 4, pp. 210–214',
      type: 'Research Paper',
      date: 'December 2026',
      doi: '10.1109/LES.2026.3214567',
      url: 'https://doi.org/10.1109/LES.2026.3214567',
      description: 'Demonstrates custom instruction set extensions on RISC-V RV32IMC processors yielding 4.2x faster AES-GCM encryption with minimal silicon overhead.',
    },
  ],
};
